[package]
name = "ddd-derive-tests"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
ddd-core = { path = "../ddd-core" }
ddd-derive = { path = "../ddd-derive" }
trybuild = "1.0"
test-case = "1.2"